#pragma once
#ifndef ERROR_CODES_H
#define ERROR_CODES_H

//#include "cx_strenc.h"

#define ERR_TITLE ("OLLIB")
#define ERR_CANT_OPEN_LICENSE ("Error Code 1")
#define ERR_CANT_CREATE_LICENSE ("Error Code 2")
#define ERR_INVALID_LICENSE ("Error Code 3")
#define ERR_NO_DEBUGGERS_ALLOWED ("Error Code 4")
#define ERR_NO_CONNECTION ("Error Code 5")
#define ERR_BAD_LICENSE_DATE ("Error Code 6")
#define ERR_INVALID_MOVEHELPER_POINTER ("Error Code 7")
#define ERR_CANT_FIND_MOVEHELPER_SIGNATURE ("Error Code 8")
#define ERR_CANT_FIND_TRACETOEXIT_SIGNATURE ("Error Code 9")
#define ERR_CANT_FIND_UTIL_CLIPTRACETOPLAYERS_SIGNATURE ("Error Code 10")
#define ERR_PREDICTION_CRASHED ("Error Code 11")
#define ERR_CANT_FIND_HELPER_GETLASTMATCHID ("Error Code 12")
#define ERR_CANT_FIND_BULLETPENETRATION_SIGNATURE ("Error Code 13")
#define ERR_CANT_FIND_SETCLANTAG_SIGNATURE ("Error Code 14")
#define ERR_CANT_FIND_M_PITCH_M_YAW_SENSITIVITY ("Error Code 15")
#define ERR_INVALID_VIEWANGLES ("Error Code 16")
#define ERR_CANT_FIND_CLIENT_STATE ("Error Code 17")
#define ERR_CANT_FIND_IS_PAUSED_SIGNATURE ("Error Code 18")
#define ERR_CANT_FIND_HOST_TICKCOUNT_SIGNATURE ("Error Code 19")
#define ERR_CANT_FIND_PREDICTION_RANDOMSEED_SIGNATURE ("Error Code 20")
#define ERR_CANT_FIND_RANDOMFLOAT ("Error Code 21")
#define ERR_CANT_FIND_RANDOMSEED ("Error Code 22")
#define ERR_CANT_FIND_GAMERULES_SIGNATURE ("Error Code 23")
#define ERR_CANT_FIND_PSEUDORANDOM_SIGNATURE ("Error Code 24")
#define ERR_CANT_FIND_INTERPOLATE_SIGNATURE ("Error Code 25")
#define ERR_CANT_FIND_INTERPOLATE_FSN_SIGNATURE ("Error Code 26")
#define ERR_CANT_FIND_SBINTERPOLATE_SIGNATURE ("Error Code 27")
#define ERR_CANT_FIND_DIDCHECKFOROCCLUSION_SIGNATURE ("Error Code 28")
#define ERR_CANT_FIND_STANDARDFILTERRULES_SIGNATURE ("Error Code 29")
#define ERR_CANT_FIND_GETCOMPRANK_SIGNATURE ("Error Code 30")
#define ERR_CANT_FIND_SETABSORIGIN_SIGNATURE ("Error Code 31")
#define ERR_CANT_FIND_SETABSANGLES_SIGNATURE ("Error Code 32")
#define ERR_CANT_FIND_SETABSVELOCITY_SIGNATURE ("Error Code 33")
#define ERR_CANT_FIND_LOOKUPPOSEPARAMETER_SIGNATURE ("Error Code 34")
#define ERR_CANT_FIND_GETPOSEPARAMETERRANGE_SIGNATURE ("Error Code 35")
#define ERR_CANT_FIND_SETPOSEPARAMETER_SIGNATURE ("Error Code 36")
#define ERR_CANT_FIND_OVERRIDEPOSTPROCESSING_SIGNATURE ("Error Code 37")
#define ERR_CANT_FIND_VIEWRENDER_SIGNATURE ("Error Code 38")
#define ERR_UNTRUSTED_LICENSE ("Error Code 39")
#define ERR_CANT_FIND_DIRECTX_TABLE ("Error Code 40")
#define ERR_CANT_FIND_DATACACHE_SETPOSEPARAM_SIG ("Error Code 41")
#define ERR_CANT_FIND_UPDATECLIENTSIDEANIMATION_SIG ("Error Code 42")
#define ERR_CANT_FIND_INVALIDATEPHYSICSRECURSIVE_SIG ("Error Code 43")
#define ERR_CANT_FIND_STANDARDFILTERRULES_SIGNATURE2 ("Error Code 44")
#define ERR_CANT_FIND_FREEENTITYBASELINES_SIGNATURE ("Error Code 45")
#define ERR_CANT_FIND_FRAMETIME_SIGNATURE ("Error Code 46")
#define ERR_CANT_FIND_VIEWMATRIX_SIGNATURE ("Error Code 47")
#define ERR_OUTDATED_CSGO_VERSION ("Error Code 48")
#define ERR_CANT_FIND_CLIENTLIST_SIGNATURE ("Error Code 49")
#define ERR_CANT_FIND_GOTV_SIGNATURE ("Error Code 50")
#define ERR_CANT_FIND_CLIENT_SIDE_ANIMATION_LIST_SIGNATURE ("Error Code 51")
#define ERR_CANT_FIND_ENABLE_INVALIDATE_BONE_CACHE_SIGNATURE ("Error Code 52")
#define ERR_CANT_FIND_GLOW_OBJECT_MANAGER_SIGNATURE ("Error Code 53")
#define ERR_CANT_FIND_RADAR_BASE_SIG ("Error Code 54")
#define ERR_CANT_FIND_IS_ENTITY_BREAKABLE_SIG1 ("Error Code 55")
#define ERR_CANT_FIND_IS_ENTITY_BREAKABLE_SIG2 ("Error Code 56")
#define ERR_CANT_FIND_IS_ENTITY_BREAKABLE_SIG3 ("Error Code 57")
#define ERR_CANT_FIND_DEMOPLAYER_CREATEMOVE_SIG ("Error Code 58")
#define ERR_CANT_FIND_ISREADY_SIG ("Error Code 59")
#define ERR_CANT_FIND_PREDICTION_PLAYER_SIG ("Error Code 60")
#define ERR_CANT_FIND_WEAPONDATAPTR_SIG ("Error Code 61")
#define ERR_CANT_FIND_WEAPONDATAPTRCALL_SIG ("Error Code 62")
#define ERR_CANT_FIND_GETCSWEAPONDATA_SIG ("Error Code 63")
#define ERR_CANT_FIND_UPDATECLIENTSIDEANIMATIONFN_SIG ("Error Code 64")
#define ERR_CANT_FIND_CAM_TO_THIRDPERSON_SIG ("Error Code 65")
#define ERR_CANT_FIND_CAM_TO_FIRSTPERSON_SIG ("Error Code 66")
#define ERR_CANT_FIND_SETUPBONES_SIG ("Error Code 67")
#define ERR_CANT_FIND_IK_INIT_SIG ("Error Code 68")
#define ERR_CANT_FIND_UPDATE_TARGETS_SIG ("Error Code 69")
#define ERR_CANT_FIND_SOLVE_DEPENDENCIES_SIG ("Error Code 70")
#define ERR_CANT_FIND_ATTACHMENT_HELPER_SIG ("Error Code 71")
#define ERR_CANT_FIND_CREATE_IK_SIG ("Error Code 72")
#define ERR_CANT_FIND_TELEPORTED_SIG ("Error Code 73")
#define ERR_CANT_FIND_BONEACCESS_FOR_NORMAL_MODELS_SIG ("Error Code 74")
#define ERR_CANT_FIND_BONEACCESS_FOR_VIEW_MODELS_SIG ("Error Code 75")
#define ERR_CANT_FIND_MODEL_BONE_COUNTER_SIG ("Error Code 76")
#define ERR_CANT_FIND_UNKNOWN_SETUPBONES_SIG ("Error Code 77")
#define ERR_CANT_FIND_SHOULD_SKIP_ANIMATION_FRAME_SIG ("Error Code 78")
#define ERR_CANT_FIND_IN_THREADED_BONE_SETUP_SIG ("Error Code 79")
#define ERR_CANT_FIND_MDLCACHE_CRITICAL_SECTION_CALL_SIG ("Error Code 80")
#define ERR_CANT_FIND_HOST_INTERVAL_PER_TICK_SIG ("Error Code 81")
#define ERR_CANT_FIND_GET_SEQUENCE_NAME_SIG ("Error code 82")
#define ERR_CANT_FIND_GET_SEQUENCE_ACTIVITY_SIG ("Error Code 83")
#define ERR_CANT_FIND_GET_SEQUENCE_ACTIVITY_NAME_FOR_MODEL_SIG ("Error Code 84")
#define ERR_CANT_FIND_GET_STRING_FOR_KEY_ACTIVITYLIST_SIG ("Error Code 85")
#define ERR_CANT_FIND_ACTIVITYLIST_NAMEFORINDEX_SIG ("Error Code 86")
#define ERR_CANT_FIND_MARK_FOR_THREADED_BONE_SETUP_SIG ("Error Code 87")
#define ERR_CANT_FIND_SEQUENCES_AVAILABLE_SIG1 ("Error Code 88")
#define ERR_CANT_FIND_SEQUENCES_AVAILABLE_SIG2 ("Error Code 89")
#define ERR_CANT_FIND_REEVALUATE_ANIMLOD_SIG ("Error Code 90")
#define ERR_CANT_FIND_PERFORM_PREDICTION_SIG ("Error Code 91")
#define ERR_CANT_FIND_PREDICTION_UPDATE_SIG ("Error Code 92")
#define ERR_CANT_FIND_PSEQDESC_SIG ("Error Code 93")
#define ERR_CANT_FIND_SV_TABLE_SIG ("Error Code 94")
#define ERR_CANT_FIND_CL_MOVE_SIG ("Error Code 95")
#define ERR_CANT_FIND_WRITE_USER_CMD ("Error Code 96")
#define ERR_CANT_FIND_USERCMDS_SIG ("Error Code 97")
#define ERR_CANT_FIND_ICLIENTENTITYLIST_SIG ("Error Code 98")
#define ERR_CANT_FIND_CL_SENDMOVE_SIG ("Error Code 99")
#define ERR_CANT_FIND_SETUPVELOCITY_RET_ADR_SIG ("Error Code 100")
#define ERR_CLAMP_HAS_NAN ("Error Code 101")
#define ERR_CANT_FIND_CL_FIREEVENTS_SIG ("Error Code 102")
#define ERR_CANT_FIND_ENABLE_ABS_RECOMPUTATIONS_SIG ("Error Code 103")
#define ERR_CANT_FIND_CSGO_WINDOW_TEXT ("Error Code 104")
#define ERR_SECURITY_HEARTBEAT_WAS_SUSPENDED ("Error Code 105")
#define ERR_SECURITY_THINK_THREAD_WAS_SUSPENDED ("Error Code 106")
#define ERR_SECURITY_VALIDATE_HEARTBEAT_WAS_SUSPENDED ("Error Code 107")
#define ERR_SECURITY_VALIDATE_HEARTBEAT_SLOW_WAS_SUSPENDED ("Error Code 108")
#define ERR_FAILED_TO_INITIALIZE_MENU ("Error Code 109")
#define ERR_CANT_FIND_PLAYER_RESOURCE_SIG ("Error Code 110")
#define ERR_CANT_FIND_UTIL_CLIPTRACETOPLAYERS2_SIGNATURE ("Error Code 111")
#define ERR_CANT_FIND_SPAWNTIME_SIGNATURE ("Error Code 112")
#define ERR_CANT_FIND_RESET_ANIMATION_STATE_SIGNATURE ("Error Code 113")
#define ERR_CANT_FIND_PROCESSONDATACHANGEDEVENTS_SIGNATURE ("Error Code 114")
#define ERR_CANT_FIND_TEMPENTS_SIGNATURE ("Error Code 115")
#define ERR_CANT_FIND_NET_SETCONVAR_CONSTRUCTOR_SIGNATURE ("Error Code 116")
#define ERR_CANT_FIND_NET_SETCONVAR_DESTRUCTOR_SIGNATURE ("Error Code 117")
#define ERR_CANT_FIND_NET_SETCONVAR_INIT_SIGNATURE ("Error Code 118")
#define ERR_CANT_FIND_NET_TIME_SIGNATURE ("Error Code 119")
#define ERR_CANT_FIND_UNKNOWN_CRC32_SIGNATURE ("Error Code 120")
#define ERR_CANT_FIND_NET_ISMULTIPLAYER_SIGNATURE ("Error Code 121")
#define ERR_CANT_FIND_RECVTABLE_DECODE_SIGNATURE ("Error Code 122")
#define ERR_CANT_FIND_SECRET1 ("Error Code 123")
#define ERR_CANT_FIND_SECRET2 ("Error Code 124")
#define ERR_CANT_FIND_CALC_ABSOLUTE_VELOCITY_SIGNATURE ("Error Code 125")
#define ERR_CANT_FIND_CALC_ABSOLUTE_POSITION_SIGNATURE ("Error Code 126")
#define ERR_CANT_FIND_SET_GROUND_ENTITY_SIGNATURE ("Error Code 127")
#define ERR_CANT_FIND_SEQUENCE_DURATION_SIGNATURE ("Error Code 128")
#define ERR_NO_HEARTBEAT_FOR_EXTENDED_TIME ("Error Code 129")
#define ERR_CANT_FIND_LOCKSTUDIOHDR_SIGNATURE ("Error Code 130")
#define ERR_CANT_FIND_SECRET3 ("Error Code 131")
#define ERR_CANT_FIND_SECRET4 ("Error Code 132")
#define ERR_CANT_FIND_SECRET5 ("Error Code 133")
#define ERR_CANT_FIND_CSPLAYER_ONLAND_SIGNATURE ("Error Code 134")
#define ERR_CANT_FIND_GAMETYPES_SIGNATURE ("Error Code 135")
#define ERR_CANT_FIND_SUPPRESS_LADDER_CHECKS_SIGNATURE ("Error Code 136")
#define ERR_CANT_FIND_SETPUNCHANGLE_SIGNATURE ("Error Code 137")
#define ERR_CANT_FIND_ISINAVEHICLE_SIGNATURE ("Error Code 138")
#define ERR_CANT_FIND_S_N_TRACEFILTERCOUNT_SIGNATURE ("Error Code 139")
#define ERR_CANT_FIND_ISCARRYINGHOSTAGE_SIGNATURE ("Error Code 140")
#define ERR_CANT_FIND_EYEVECTORS_SIGNATURE ("Error Code 141")
#define ERR_CANT_FIND_CREATESTUCKTABLE_SIGNATURE ("Error Code 142")
#define ERR_CANT_FIND_CVOICESTATUS_SIGNATURE ("Error Code 143")
#define ERR_CANT_FIND_LEVELSHUTDOWNPREENTITYALLSYSTEMS_SIGNATURE ("Error Code 144")
#define ERR_CANT_FIND_VAC_SIGNATURE1 ("Error Code 145")
#define ERR_CANT_FIND_VAC_SIGNATURE2 ("Error Code 146")
#define ERR_CANT_FIND_VAC_SIGNATURE3 ("Error Code 147")
#define ERR_CANT_FIND_RENDERBEAMS ("Error Code 148")
#define ERR_CANT_FIND_MUZZLEFLASH_SIGNATURE ("Error Code 149")
#define ERR_CANT_FIND_PREDICTIONUPDATE_HLTV_SIGNATURE ("Error Code 150")
#define ERR_CANT_FIND_GETBONEPOSITION_SIGNATURE ("Error Code 151")
#define ERR_CANT_FIND_LOOKUPBONE_SIGNATURE ("Error Code 152")
#define ERR_CANT_FIND_g_vecRenderOrigin ("Error Code 153")
#define ERR_CANT_FIND_CACHEVEHICLEVIEW_SIGNATURE ("Error Code 154")
#define ERR_CANT_FIND_BASE_CALCVIEW_SIGNATURE ("Error Code 155")
#define ERR_CANT_FIND_IRONSIGHT_CONTROLLER_OFFSET ("Error Code 156")
#define ERR_CANT_FIND_ISINIRONSIGHT_SIGNATURE ("Error Code 157")
#define ERR_CANT_FIND_LEVELINITPREENTITYALLSYSTEMS_SIGNATURE ("Error Code 158")
#define ERR_CANT_FIND_LEVELINITPREENTITY_GAMESTATS_SIGNATURE ("Error Code 159")
#define ERR_CANT_FIND_MODEL_RENDER_GLOW_SIGNATURE ("Error Code 160")
#define ERR_CANT_FIND_MODEL_RENDER_GLOW_VAC_SIGNATURE ("Error Code 161")
#define ERR_CANT_MAP_SHARED_FILE ("Error Code 162")
#define ERR_CANT_ALLOCATE_MEMORY_TO_POINTERS ("Error Code 163")
#define ERR_CANT_FIND_SET_DORMANT_SIGNATURE ("Error Code 164")
#define ERR_CANT_FIND_CVARCHECK_SIGNATURE ("Error Code 165")

#ifdef PRODUCTION

#ifdef MUTINY_FRAMEWORK
#include "VMProtectDefs.h"
void THROW_ERROR_TO_MUTINY(const char* str, bool takeSS = false);
#define LOG_MESSAGE(a) THROW_ERROR(VMP_ENCDECSTRINGA(a))
#define THROW_ERROR(str) THROW_ERROR_TO_MUTINY(VMP_ENCDECSTRINGA(str));
#define THROW_ERROR_EMER(str) THROW_ERROR_TO_MUTINY(VMP_ENCDECSTRINGA(str), true);
#else
#define THROW_ERROR(str) 
#define THROW_ERROR_EMER(str) 
#endif

#else

#ifndef MUTINY
inline __declspec(noinline) void THROW_ERROR(const char* errorcode)
{
	MessageBox(NULL, errorcode, ERR_TITLE, MB_OK);
}
inline __declspec(noinline) void THROW_ERROR_EMER(const char* errorcode)
{
	MessageBox(NULL, errorcode, ERR_TITLE, MB_OK);
}
#else
#ifdef MUTINY_FRAMEWORK
//#include "C:\Developer\Sync\Framework\Files\Logging\Logging.h"
#include "VMProtectDefs.h"
void THROW_ERROR_TO_MUTINY(const char* str, bool takeSS = false);
#define LOG_MESSAGE(a) THROW_ERROR(VMP_ENCDECSTRINGA(a))
#define THROW_ERROR(str) THROW_ERROR_TO_MUTINY(VMP_ENCDECSTRINGA(str));
#define THROW_ERROR_EMER(str) THROW_ERROR_TO_MUTINY(VMP_ENCDECSTRINGA(str), true);
#else
#ifdef NO_MUTINY_HEARTBEAT
inline __declspec(noinline) void THROW_ERROR(const char* errorcode)
{
	MessageBox(NULL, errorcode, ERR_TITLE, MB_OK);
}
inline __declspec(noinline) void THROW_ERROR_EMER(const char* errorcode)
{
	MessageBox(NULL, errorcode, ERR_TITLE, MB_OK);
}
#else
//#include "C:\DeveloperFramework\\Framework\Logging\Logging.h"
//#include "VMProtectDefs.h"
void THROW_ERROR_TO_MUTINY(const char* str, bool takeSS = false);
#define LOG_MESSAGE(a) THROW_ERROR(VMP_ENCDECSTRINGA(a))
#define THROW_ERROR(str) THROW_ERROR_TO_MUTINY(VMP_ENCDECSTRINGA(str));
#define THROW_ERROR_EMER(str) THROW_ERROR_TO_MUTINY(VMP_ENCDECSTRINGA(str), true);
#endif
#endif
#endif
#endif
#endif
