#pragma once

#include <string>

#define	HITGROUP_HEAD_FLAG      (1<<0)
#define	HITGROUP_CHEST_FLAG		(1<<1)
#define	HITGROUP_STOMACH_FLAG	(1<<2)
#define HITGROUP_LEFTARM_FLAG	(1<<3)
#define HITGROUP_RIGHTARM_FLAG	(1<<4)
#define HITGROUP_LEFTLEG_FLAG	(1<<5)
#define HITGROUP_RIGHTLEG_FLAG	(1<<6)
#define HITGROUP_ALL_FLAG (HITGROUP_HEAD_FLAG | HITGROUP_CHEST_FLAG | HITGROUP_STOMACH_FLAG | HITGROUP_LEFTARM_FLAG | HITGROUP_RIGHTARM_FLAG | HITGROUP_LEFTLEG_FLAG | HITGROUP_RIGHTLEG_FLAG)

#define TARGET_HEAD_FLAG (1<<0)
#define TARGET_TORSO_FLAG (1<<1)
#define TARGET_ARMSHANDS_FLAG (1<<2)
#define TARGET_LEGSFEET_FLAG (1<<3)
#define TARGET_ALL_FLAG (TARGET_HEAD_FLAG | TARGET_TORSO_FLAG | TARGET_ARMSHANDS_FLAG | TARGET_LEGSFEET_FLAG)

enum BONE_GROUPS
{
	BONE_GROUP_HEADNECK = 0,
	BONE_GROUP_CHESTTORSOPELVIS,
	BONE_GROUP_SHOULDERARMSHANDS,
	BONE_GROUP_LEGSFEET
};

enum Hitboxes : int
{
	HITBOX_HEAD,
	//HITBOX_NECK, ONLY ON ENGINE_VERSION < 13635
	HITBOX_LOWER_NECK,
	HITBOX_PELVIS,
	HITBOX_BODY,
	HITBOX_THORAX,
	HITBOX_CHEST,
	HITBOX_UPPER_CHEST,
	HITBOX_LEFT_THIGH,
	HITBOX_RIGHT_THIGH,
	HITBOX_LEFT_CALF,
	HITBOX_RIGHT_CALF,
	HITBOX_LEFT_FOOT,
	HITBOX_RIGHT_FOOT,
	HITBOX_LEFT_HAND,
	HITBOX_RIGHT_HAND,
	HITBOX_LEFT_UPPER_ARM,
	HITBOX_LEFT_FOREARM,
	HITBOX_RIGHT_UPPER_ARM,
	HITBOX_RIGHT_FOREARM,
	HITBOX_MAX
};

extern std::string get_hitbox_name(int id);