#pragma once

#include <Windows.h>


enum hook_types : int
{
	_NOTHOOKED = -2,
	_UNSET = -1,
	_HookLevelShutdownAndInitPreEntity,
	_Netchan,
	_MessageHandler,
	_Gamerules,
	_BasePlayer,
	_BaseRenderable,
	_BaseNetworkable,
	_MolotovIncendiary,
	_ClientEntityList,
	_ClientMode,
	_Client,
	_Prediction,
	_Engine,
	_Muzzleflash,
	_EffectDispatch,
	_EngineClientSound,
	_Surface,
	_VPanel,
	_ModelRender,
	_ClientState,
	_TempEnts,
	_Beams,
	_GameEventListener,
	_DirectX,
	_StudioRender,
	_RenderView,
	_IInput,
	_MoveHelperClientHook,
	_EyeAnglesProxyX,
	_EyeAnglesProxyY,
	_EyeAnglesProxyZ,
	_VelocityModifier,
	_Tickbase,
	_ClientLeafSystem,
	_PoseParameter,
	_BasePlayerAnimState,
	_FlashDuration,
	_VPhysicsCollisionState,
	_BSPQuery,
	_GameMovement,
	_ModelInfoClient,
	_SteamGameCoordinator,
	_SimulationTime
	//_PostPoneFireReadyTime,
};
